# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

stages:
  - version
  - build
  - package
  - release

version:
  stage: version
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - release next-version --allow-current > .next-version
    - echo Next version is $(<.next-version)
  artifacts:
    paths:
      - .next-version


build:
  stage: build
  image: registry.gitlab.com/caspermeijn/docker-images/pinetime-build:latest
  script:
    - newt upgrade
    - newt build boot-pinetime
    - newt build klok-pinetime
    - newt create-image klok-pinetime $(<.next-version)
  artifacts:
    paths:
      - bin/targets/klok-pinetime/app/apps/klok/klok.img
  cache:
    paths:
      - repos

reuse:
  stage: build
  image:
    name: fsfe/reuse:latest
    entrypoint: [""]
  script:
    - reuse lint
  needs: []

conventional-commits:
  stage: build
  image:
    name: rust
  before_script:
    - cargo install convco
  script:
    - git fetch origin
    - convco check origin/master..HEAD
  needs: []

package:
  stage: package
  image: python:3.8
  before_script:
    - pip install adafruit-nrfutil
  script:
    - cp bin/targets/klok-pinetime/app/apps/klok/klok.img klok.img
    - mkdir dfu && pushd dfu
    - cp ../klok.img klok_dfu.bin
    - adafruit-nrfutil dfu genpkg --dev-type 0x0052 --application klok_dfu.bin klok_dfu.zip
    - popd
    - echo "RELEASE_BASE_URL=https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/jobs/$CI_JOB_ID/artifacts/" > release_info
    - echo "RELEASE_SHA=$CI_COMMIT_SHA" >> release_info
    - echo "RELEASE_VERSION=$(<.next-version)" >> release_info
  needs:
    - version
    - build
  artifacts:
    paths:
      - release_info
      - klok.img
      - dfu/klok_dfu.bin
      - dfu/klok_dfu.zip

release:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - . release_info
    - release -v
    - release tag
  when: manual
  only:
    - master

deploy:
  stage: release
  image: registry.gitlab.com/juhani/go-semrel-gitlab:v0.21.1
  script:
    - . release_info
    - release -v
    - release --ci-commit-tag v$RELEASE_VERSION add-download-link -n "Klok PineTime image" -u ${RELEASE_BASE_URL}/klok.img -d "Klok PineTime image v$RELEASE_VERSION"
    - release --ci-commit-tag v$RELEASE_VERSION add-download-link -n "Klok PineTime dfu binary" -u ${RELEASE_BASE_URL}/dfu/klok_dfu.bin -d "Klok PineTime dfu binary v$RELEASE_VERSION"
    - release --ci-commit-tag v$RELEASE_VERSION add-download-link -n "Klok PineTime dfu distribution zip" -u ${RELEASE_BASE_URL}/dfu/klok_dfu.zip -d "Klok PineTime dfu distribution zip v$RELEASE_VERSION"
  only:
    - tags

rustfmt:
  stage: build
  image: registry.gitlab.com/caspermeijn/docker-images/pinetime-build:latest
  before_script:
    - rustup component add rustfmt
  script:
    - newt upgrade mynewt-rust
    - cd apps/klok && cargo fmt --all -- --check
  needs: []

