# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

project.name: "klok"

project.repositories:
    - apache-mynewt-core
    - apache-mynewt-mcumgr
    - mynewt-rust

repository.apache-mynewt-core:
    type: github
    vers: 20c0af23fd8d94a8499c7443ff8551225ffa726e-commit
    user: caspermeijn
    repo: mynewt-core

repository.apache-mynewt-mcumgr:
    type: github
    vers: 68c6620085153db9a59a325896168d73f7ac0338-commit
    user: caspermeijn
    repo: mynewt-mcumgr

repository.mynewt-rust:
    type: github
    vers: 402851781ef67b2c11a414f5c3919176d32105eb-commit
    user: caspermeijn
    repo: mynewt-rust
