# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

project.name: "klok"

project.repositories:
    - apache-mynewt-core
    - mynewt-rust

repository.apache-mynewt-core:
    type: github
    vers: 424507b45ad0cdb69668f5bc7fd51d86afd2a70d-commit
    user: caspermeijn
    repo: mynewt-core

repository.mynewt-rust:
    type: github
    vers: a83081000501f3ae29b18aa8eb9b8ebfede0ae0f-commit
    user: caspermeijn
    repo: mynewt-rust
