# Copyright (C) 2020 Casper Meijn <casper@meijn.net>
#
# SPDX-License-Identifier: CC0-1.0

project.name: "klok"

project.repositories:
    - apache-mynewt-core
    - apache-mynewt-mcumgr
    - mynewt-rust

repository.apache-mynewt-core:
    type: github
    vers: 0-dev
    user: apache
    repo: mynewt-core

repository.apache-mynewt-mcumgr:
    type: github
    vers: 68c6620085153db9a59a325896168d73f7ac0338-commit
    user: caspermeijn
    repo: mynewt-mcumgr

repository.mynewt-rust:
    type: github
    vers: d12d63d3350f01ef7d12b61ba4eaddebedb9c9f4-commit
    user: caspermeijn
    repo: mynewt-rust
